baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[minify]
    disableHTML = true

[markup.goldmark.renderer]
    unsafe = true 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.meta]
    favicon = true
